[package]
name = "liteipc"
version = "0.1.0"
authors = ["lqdev <liquidekgaming@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.5", features = ["lua52", "module"] }
subprocess = "0.2.6"
